[project]
name = "cuma"
version = "1.0.0"
description = "CuMA: Aligning LLMs with Sparse Cultural Values via Demographic-Aware Mixture of Adapters (ACL 2026)"
readme = "README.md"
requires-python = ">=3.10, <3.13"
license = {text = "Apache-2.0"}
authors = [
    {name = "Ao Sun", email = "sunao@seu.edu.cn"},
    {name = "Xiaoyu Wang"},
    {name = "Zhe Tan"},
    {name = "Yu Li"},
    {name = "Jiachen Zhu"},
    {name = "Yuheng Jia", email = "yhjia@seu.edu.cn"},
    {name = "Shu Su", email = "sushu@seu.edu.cn"},
]

[project.urls]
Homepage = "https://github.com/Throll/CuMA"
Paper = "https://aclanthology.org/2026.acl-long.XXX/"
dependencies = [
    "accelerate>=1.10.1",
    "bitsandbytes>=0.48.0",
    "datasets>=4.2.0",
    "fire>=0.7.1",
    "flashinfer-python==0.4.1",
    "ipykernel>=7.0.1",
    "ipython>=8.37.0",
    "jsonlines>=4.0.0",
    "jupyter>=1.1.1",
    "matplotlib>=3.10.7",
    "nltk>=3.9.2",
    "openai==1.99.1",
    "peft>=0.17.1",
    "safetensors>=0.6.2",
    "scikit-learn>=1.7.2",
    "seaborn>=0.13.2",
    "tensorboard>=2.20.0",
    "trl>=0.24.0",
    "torch>=2.3.0",
    "transformers==4.57.1",
    "triton==3.4.0",
    "pandas>=2.3.3",
    "deepspeed>=0.18.2",
    "adjusttext>=1.3.0",
]

[tool.uv]
prerelease = "allow"

[[tool.uv.index]]
url = "https://mirrors.aliyun.com/pypi/simple/"

